name = "ovia-home"
compatibility_date = "2023-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = true
route = "*/*"
zone_id = ""

[ssl]
strict = true
certificate_manager = true

[build]
command = "cd frontend && npm install && npm run build"
pages_build_output_dir = "frontend/build"

[vars]
SPREADSHEET_ID = "1Za8CAl0QQmYLAub6AFJUdtiK5Qry1Ono8qyYwE5EWfI"

[site]
bucket = "./frontend/build"