name = "ovia-home"
compatibility_date = "2024-09-01"

# Built for Cloudflare Pages Functions + D1
# Note: In both Production and Preview environments, make sure to set 
# the D1 binding name as 'DB' in Pages Settings → Functions → D1 Bindings

[[d1_databases]]
binding = "DB"
database_name = "database1"        # Name created in Cloudflare D1 dashboard
database_id = "<D1_DATABASE_ID>"   # TODO: Replace with your actual D1 database ID

[vars]
ADMIN_USER = "admin"
ADMIN_PASS = "change-me"