name = "ovia-home-web-page"
compatibility_date = "2023-01-01"

[build]
command = "npm install && npm run build"
pages_build_output_dir = "frontend/build"

[vars]
SPREADSHEET_ID = "1Za8CAl0QQmYLAub6AFJUdtiK5Qry1Ono8qyYwE5EWfI"

[pages]
build_output_dir = "frontend/build"